### ISSUE TITLE
Couple of missing files error

### ISSUE THREAD

**Issue by derekang** [natzar/Stripe-Pad#11]
**Describe the bug**
Trying to install stripepad and encounted the below errors. Seems some files are missing from the repository.

**To Reproduce**
1. Go to https://www.travelmarketingchina.com/
2. See error

**Expected behavior**
No errors

**Error**
Warning: include_once(/home4/b3f1s0q2/travelmarketingchina.com/core/ModelBase.php): failed to open stream: No such file or directory in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 42

Warning: include_once(): Failed opening '/home4/b3f1s0q2/travelmarketingchina.com/core/ModelBase.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 42

Warning: include_once(/home4/b3f1s0q2/travelmarketingchina.com/core/SPDO.php): failed to open stream: No such file or directory in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 43

Warning: include_once(): Failed opening '/home4/b3f1s0q2/travelmarketingchina.com/core/SPDO.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 43

Warning: include_once(/home4/b3f1s0q2/travelmarketingchina.com/core/View.php): failed to open stream: No such file or directory in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 44

Warning: include_once(): Failed opening '/home4/b3f1s0q2/travelmarketingchina.com/core/View.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 44

Fatal error: Uncaught Error: Class 'ModelBase' not found in /home4/b3f1s0q2/travelmarketingchina.com/app/models/sampleModel.php:17 Stack trace: #0 /home4/b3f1s0q2/travelmarketingchina.com/load.php(85): include() #1 /home4/b3f1s0q2/travelmarketingchina.com/index.php(26): require_once('/home4/b3f1s0q2...') #2 {main} thrown in /home4/b3f1s0q2/travelmarketingchina.com/app/models/sampleModel.php on line 17

Warning: include(app/themes/base-dark/errors/error.php): failed to open stream: No such file or directory in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 77

Warning: include(): Failed opening 'app/themes/base-dark/errors/error.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 77

Fatal error: Uncaught ErrorException: include(app/themes/base-dark/errors/error.php): failed to open stream: No such file or directory in /home4/b3f1s0q2/travelmarketingchina.com/load.php:63 Stack trace: #0 /home4/b3f1s0q2/travelmarketingchina.com/load.php(63): {closure}(2, 'include(app/the...', '/home4/b3f1s0q2...', 63, Array) #1 /home4/b3f1s0q2/travelmarketingchina.com/load.php(63): include() #2 [internal function]: {closure}() #3 {main} thrown in /home4/b3f1s0q2/travelmarketingchina.com/load.php on line 63

**Comment by natzar** [comment]
It should be fixed now.
